version: '3.8'

services:
  catthreadservice:
    image: catthreadservice
    build:
      context: ./MicroServices/CatThreadService
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=forum_cat_thread;User=root;Password=;

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: forum_cat_thread
    ports:
      - "3036:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
